version: '3'
services:
  go-tour-web:
    container_name: go-tour-web
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
      # - /var/www/media:/app/media
