# Generated by Django 4.2.5 on 2023-09-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', models.TextField(blank=True, null=True)),
                ('objectid', models.IntegerField(blank=True, db_column='OBJECTID', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', null=True)),
                ('datetimes', models.DateTimeField(blank=True, db_column='DateTimeS', null=True)),
                ('elevation', models.FloatField(blank=True, db_column='Elevation', null=True)),
                ('code', models.IntegerField(blank=True, db_column='Code', null=True)),
                ('full_name', models.CharField(blank=True, db_column='Full_Name', null=True)),
                ('short_name', models.CharField(blank=True, db_column='Short_Name', null=True)),
                ('zone', models.CharField(blank=True, db_column='Zone', null=True)),
                ('wereda', models.CharField(blank=True, db_column='Wereda', null=True)),
                ('kebele', models.CharField(blank=True, db_column='Kebele', null=True)),
                ('locality_n', models.CharField(blank=True, db_column='Locality_N', null=True)),
                ('organizati', models.CharField(blank=True, db_column='Organizati', null=True)),
                ('destinatio', models.CharField(blank=True, db_column='Destinatio', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', null=True)),
                ('area_sqkm', models.CharField(blank=True, db_column='Area_sqkm', null=True)),
                ('yearly_est', models.CharField(blank=True, db_column='Yearly_Est', null=True)),
                ('unesco_reg', models.CharField(blank=True, db_column='UNESCO_Reg', null=True)),
                ('descriptio', models.CharField(blank=True, db_column='Descriptio', null=True)),
                ('photo_no', models.CharField(blank=True, db_column='Photo_No', null=True)),
                ('photo_loca', models.CharField(blank=True, db_column='Photo_Loca', null=True)),
                ('site_des_a', models.CharField(blank=True, db_column='Site_Des_A', null=True)),
                ('amharic', models.CharField(blank=True, db_column='Amharic', null=True)),
                ('english', models.CharField(blank=True, db_column='English', null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, db_column='Y', null=True)),
            ],
            options={
                'db_table': 'destinations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('geom', models.TextField(blank=True, null=True)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.IntegerField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, null=True)),
                ('short_name', models.CharField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, null=True)),
                ('wereda', models.CharField(blank=True, null=True)),
                ('kebele', models.CharField(blank=True, null=True)),
                ('phone_line', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('website', models.CharField(blank=True, null=True)),
                ('service_ty', models.CharField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, null=True)),
                ('moto', models.CharField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
    ]
